<?php

namespace Classifier;

use PHPUnit\Framework\TestCase;
use App\Classifier\BayesClassifier;

final class BayesClassifierTest extends TestCase
{
    public function testDictionaryUpdate()
    {
        $classifier = new BayesClassifier();

        $classifier->updateDictionary("one");
        $classifier->updateDictionary("two");
        $classifier->updateDictionary("three");
        $classifier->updateDictionary("three");
        $classifier->updateDictionary("five");


        $this->assertSame(["one", "two", "three", "five"], $classifier->dictionary);
    }

    public function testLearnSingle()
    {
        $classifier = new BayesClassifier();

        $classifier->learn("lorem ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum, Lorem ipsum dolor sit amet");
        $category = $classifier->fetchCategory("lorem ipsum");

        
        $this->assertSame(["lorem","ipsum", "dolor", "sit", "amet", "consectetur", "adipiscing", "elit"], $classifier->dictionary);
        $this->assertSame(1, $category->getDocumentCount());
        $this->assertSame(15, $category->getTermCount());
        $this->assertSame(["lorem" => 3,"ipsum" => 3, "dolor" => 2, "sit" => 2, "amet" => 2, "consectetur" => 1, "adipiscing" => 1, "elit" => 1], $category->getTermFrequencies());
    }

    public function testLearnMultiple()
    {
        $classifier = new BayesClassifier();

        $classifier->learn("lorem ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum, Lorem ipsum dolor sit amet");
        $classifier->learn("lorem ipsum", "Lorem ipsum ipsum, amet amet, dolor sit");
        $classifier->learn("not lorem ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum, Lorem ipsum dolor sit amet. Bacon bacon chuck");

        $this->assertSame(["lorem","ipsum", "dolor", "sit", "amet", "consectetur", "adipiscing", "elit", "bacon", "chuck"], $classifier->dictionary);

        $categoryLoremIpsum = $classifier->fetchCategory("lorem ipsum");
        $this->assertSame(2, $categoryLoremIpsum->getDocumentCount());
        $this->assertSame(22, $categoryLoremIpsum->getTermCount());
        $this->assertSame(["lorem" => 4,"ipsum" => 5, "dolor" => 3, "sit" => 3, "amet" => 4, "consectetur" => 1, "adipiscing" => 1, "elit" => 1], $categoryLoremIpsum->getTermFrequencies());

        $categoryNotLoremIpsum = $classifier->fetchCategory("not lorem ipsum");
        $this->assertSame(1, $categoryNotLoremIpsum->getDocumentCount());
        $this->assertSame(18, $categoryNotLoremIpsum->getTermCount());
        $this->assertSame(["lorem" => 3,"ipsum" => 3, "dolor" => 2, "sit" => 2, "amet" => 2, "consectetur" => 1, "adipiscing" => 1, "elit" => 1, "bacon" => 2, "chuck" => 1], $categoryNotLoremIpsum->getTermFrequencies());
    }

    public function testCalculateCategoryProbabilities()
    {
        $classifier = new BayesClassifier();

        $classifier->learn("numbers", "five six seven eight");
        $classifier->learn("words", "one two three four");
        $category = $classifier->fetchCategory("numbers");

        $oneProbability = $classifier->calculateCategoryProbabilities("one two five six");

        $this->assertSame($oneProbability, ["numbers" => -9.246479418592056, "words" => -9.246479418592056]);
    }

    public function testClassify()
    {
        $classifier = new BayesClassifier();

        $classifier->learn("lorem ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis lacus dictum leo dictum pulvinar. Vestibulum quis ligula sem. Mauris quis massa at erat efficitur sagittis. Morbi sollicitudin dui ac quam dapibus, et convallis nisl pulvinar. Nunc finibus gravida neque vitae malesuada. Quisque non dictum dolor. Mauris at libero eget tortor dignissim suscipit. Sed ut accumsan arcu. Etiam a eros nisl. Praesent tellus augue, cursus eget laoreet a, rhoncus non ex. Curabitur libero turpis, ultrices et orci venenatis, vulputate imperdiet velit. Aenean eget magna in neque ultrices vulputate. Vivamus pharetra augue vitae quam feugiat, vitae congue orci vehicula. Praesent mattis sapien sit amet scelerisque scelerisque. Etiam vitae euismod sapien. Praesent mollis metus sit amet bibendum sodales. Vestibulum odio turpis, vestibulum eu convallis non, elementum sit amet neque. Etiam varius euismod metus, et condimentum velit aliquam eu. Aenean iaculis sollicitudin urna eu pharetra. Vestibulum eget fermentum leo. Sed tincidunt urna a tortor finibus, quis accumsan nibh pharetra. Maecenas elementum leo vulputate ipsum cursus efficitur. Ut viverra consequat nulla, sed vestibulum mi sagittis id. Sed enim neque, gravida non rhoncus at, mattis sit amet mauris. Curabitur ornare sit amet eros et aliquet. Donec diam turpis, fringilla id lacus id, imperdiet pulvinar sapien. Nam ex enim, imperdiet et porta quis, eleifend a dolor. In hac habitasse platea dictumst. Nam suscipit congue lacus et vulputate. Sed fermentum laoreet erat, nec scelerisque ligula ultrices eu. Maecenas a consectetur augue, vitae eleifend velit. Mauris accumsan ligula dui, vitae faucibus lacus finibus sit amet. In finibus suscipit lacus, id consectetur mauris porta a. Proin egestas urna in mi viverra pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras quam nibh, laoreet quis massa ut, volutpat ultrices neque. Proin a commodo felis, eget iaculis erat. Sed gravida, magna non consectetur elementum, sapien velit convallis eros, et facilisis diam justo vitae velit. Donec nec scelerisque felis, vel ullamcorper ligula. Pellentesque commodo bibendum diam, eu mollis velit vehicula quis. Sed leo ante, lobortis vitae pulvinar a, rutrum nec ligula. Ut molestie mi eu ultrices porta. Donec pulvinar semper justo et euismod. Sed odio urna, lacinia eget tempus at, rutrum et diam. Integer sed volutpat est. Suspendisse a tempus felis. Sed tempus accumsan vulputate. Quisque congue convallis eros ut lacinia. Nullam vel cursus nunc, ut finibus lorem. Mauris faucibus tellus eget lobortis congue. ");
        $classifier->learn("lorem ipsum", "Dolor sit amet  In iaculis suscipit dictum. Nam tristique luctus neque, et mollis tortor efficitur ut. Aliquam bibendum, nibh vel feugiat elementum, ligula dui tempor neque, nec feugiat libero massa sit amet ex. Duis odio libero, iaculis at ante ac, volutpat facilisis dolor. Sed blandit faucibus felis sit amet facilisis.Aenean finibus massa non augue dictum, in feugiat velit volutpat. Maecenas dignissim efficitur lectus, nec luctus felis dapibus vel. Nunc libero tellus, gravida sed placerat sit amet, convallis vulputate ex. In condimentum, orci eget viverra pulvinar, dui magna sodales orci, id fermentum lorem sapien ac est. Integer ac euismod tellus. Aliquam erat volutpat. Suspendisse accumsan nisi turpis, vel pharetra libero vulputate vel.Vivamus varius mauris in turpis venenatis gravida eget a risus. Fusce lacinia at lorem nec condimentum. Duis auctor neque urna, laoreet ornare quam luctus lacinia. Donec semper pulvinar sem id imperdiet. Nulla consectetur quis felis eget eleifend. Aliquam ut lorem sit amet risus dapibus sagittis nec eu enim. Fusce risus lectus, eleifend sed egestas sed, vulputate vel purus. Maecenas a arcu et elit vulputate fringilla. Sed feugiat, arcu in fermentum accumsan, ante elit aliquam urna, vel fringilla nulla magna et diam. Aliquam laoreet odio vel pretium suscipit.Quisque sit amet orci quis dui tincidunt cursus. Nunc in mollis nunc, et interdum ipsum. Praesent nec nibh non augue tristique pellentesque et eget quam. Donec semper ipsum nec quam vehicula auctor. Mauris scelerisque tellus nec rhoncus bibendum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam venenatis vel ex condimentum iaculis. Quisque pretium quam eu nulla tincidunt, eget pellentesque ex luctus. Curabitur at ligula sollicitudin, molestie dui vel, volutpat tellus. Phasellus eu accumsan nisl, a aliquam urna. Nam sed rhoncus metus.Quisque sed augue quis odio sollicitudin congue. Proin sollicitudin lectus vitae lectus fermentum, ac mollis nisi feugiat. Nam ornare leo vel gravida tristique. Nulla facilisi. Vestibulum nec augue lorem. Praesent ultricies, est et hendrerit tempor, nunc ex gravida arcu, sed rutrum massa lectus ut purus. Integer porta consectetur justo vel luctus. Nulla facilisi. Curabitur nulla nulla, pharetra sed purus ac, finibus laoreet neque. Vestibulum ut dolor aliquam ipsum faucibus auctor. Cras vel aliquam magna.Cras eget bibendum odio. Aenean luctus orci et gravida mollis. Nullam accumsan felis in nibh tincidunt tempor. Quisque faucibus, lectus ultrices sollicitudin laoreet, est est lacinia dui, sit amet fermentum nisl neque nec ante. ");
        $classifier->learn("pirate ipsum", "Nipper keelhaul red ensign shrouds booty scurvy maroon wherry spirits cutlass. Clipper line gally Privateer scourge of the seven seas crow's nest Corsair sutler galleon hardtack. Starboard lad capstan lookout brig deadlights yawl pirate hornswaggle nipper. Fore take a caulk piracy grog nipperkin man-of-war squiffy dead men tell no tales scourge of the seven seas hogshead. Wherry landlubber or just lubber carouser fire in the hole red ensign marooned starboard sheet pirate execution dock. Fire in the hole doubloon bounty fathom execution dock me splice the main brace tender run a rig dead men tell no tales. American Main run a shot across the bow Blimey fore pillage measured fer yer chains Corsair swab mizzen lad. Line aye tack grapple hempen halter splice the main brace jury mast starboard booty killick. Reef sails Sea Legs snow dance the hempen jig capstan haul wind salmagundi yardarm jib case shot. Killick pinnace square-rigged Shiver me timbers loaded to the gunwalls topmast tack sutler lugger snow. Grog draft gibbet black spot chase guns Plate Fleet execution dock rigging provost parley. Shrouds no prey, no pay aft long boat scallywag Spanish Main fire ship landlubber or just lubber ho Jack Tar. Starboard lad capstan lookout brig deadlights yawl pirate hornswaggle nipper. Fore take a caulk piracy grog nipperkin man-of-war squiffy dead men tell no tales scourge of the seven seas hogshead. Wherry landlubber or just lubber carouser fire in the hole red ensign marooned starboard sheet pirate execution dock. Fire in the hole doubloon bounty fathom execution dock me splice the main brace tender run a rig dead men tell no tales. American Main run a shot across the bow Blimey fore pillage measured fer yer chains Corsair swab mizzen lad. Line aye tack grapple hempen halter splice the main brace jury mast starboard booty killick. Reef sails Sea Legs snow dance the hempen jig capstan haul wind salmagundi yardarm jib case shot.Execution dock lateen sail spyglass Shiver me timbers knave swing the lead strike colors flogging piracy interloper.Killick pinnace square-rigged Shiver me timbers loaded to the gunwalls topmast tack sutler lugger snow.Red ensign weigh anchor aye crack Jennys tea cup belay jolly boat warp Arr hardtack grapple.Port spike lateen sail driver Davy Jones' Locker black spot grog gunwalls Jack Tar pressgang. Log run a rig cackle fruit lookout Brethren of the Coast Spanish Main draft red ensign cable transom. Execution dock lateen sail spyglass Shiver me timbers knave swing the lead strike colors flogging piracy interloper.");
        $classifier->learn("pirate ipsum", "Yellow Jack parrel code of conduct list piracy crimp bucko rum coffer bilge. Lee skysail matey tackle Jack Ketch jack aft line Jack Tar boom. Red ensign weigh anchor aye crack Jennys tea cup belay jolly boat warp Arr hardtack grapple.Port spike lateen sail driver Davy Jones' Locker black spot grog gunwalls Jack Tar pressgang. Log run a rig cackle fruit lookout Brethren of the Coast Spanish Main draft red ensign cable transom. Execution dock lateen sail spyglass Shiver me timbers knave swing the lead strike colors flogging piracy interloper.Killick pinnace square-rigged Shiver me timbers loaded to the gunwalls topmast tack sutler lugger snow. Grog draft gibbet black spot chase guns Plate Fleet execution dock rigging provost parley. Shrouds no prey, no pay aft long boat scallywag Spanish Main fire ship landlubber or just lubber ho Jack Tar.Nipper keelhaul red ensign shrouds booty scurvy maroon wherry spirits cutlass. Clipper line gally Privateer scourge of the seven seas crow's nest Corsair sutler galleon hardtack. Starboard lad capstan lookout brig deadlights yawl pirate hornswaggle nipper. Fore take a caulk piracy grog nipperkin man-of-war squiffy dead men tell no tales scourge of the seven seas hogshead. Wherry landlubber or just lubber carouser fire in the hole red ensign marooned starboard sheet pirate execution dock. Fire in the hole doubloon bounty fathom execution dock me splice the main brace tender run a rig dead men tell no tales. American Main run a shot across the bow Blimey fore pillage measured fer yer chains Corsair swab mizzen lad. Line aye tack grapple hempen halter splice the main brace jury mast starboard booty killick. Reef sails Sea Legs snow dance the hempen jig capstan haul wind salmagundi yardarm jib case shot. Port spike lateen sail driver Davy Jones' Locker black spot grog gunwalls Jack Tar pressgang. Log run a rig cackle fruit lookout Brethren of the Coast Spanish Main draft red ensign cable transom. Execution dock lateen sail spyglass Shiver me timbers knave swing the lead strike colors flogging piracy interloper.Killick pinnace square-rigged Shiver me timbers loaded to the gunwalls topmast tack sutler lugger snow. Grog draft gibbet black spot chase guns Plate Fleet execution dock rigging provost parley. Shrouds no prey, no pay aft long boat scallywag Spanish Main fire ship landlubber or just lubber ho Jack Tar.Nipper keelhaul red ensign shrouds booty scurvy maroon wherry spirits cutlass. Clipper line gally Privateer scourge of the seven seas crow's nest Corsair sutler galleon hardtack.");
        $classifier->learn("bacon ipsum", "Swine cillum quis incididunt.  Exercitation laboris leberkas picanha pork est filet mignon salami shankle.  Ham hock kevin reprehenderit non dolore, spare ribs ea nisi sirloin ribeye cillum velit.  Sausage elit pariatur, hamburger turducken sunt ex occaecat laboris pastrami magna ut.  Filet mignon venison chicken pork belly pastrami sirloin ea landjaeger.  Ad in excepteur ham hock id turkey, andouille aliquip anim consequat culpa aliqua short ribs meatloaf. Kielbasa short loin magna pastrami nostrud short ribs labore sausage.  Mollit ground round boudin, minim eu frankfurter bacon.  Exercitation turducken fatback, velit sausage labore shankle ut brisket adipisicing occaecat.  Ex ipsum venison alcatra fatback minim chicken filet mignon dolor, salami velit ut bacon non rump.  Eiusmod cillum drumstick meatloaf, brisket rump spare ribs shankle tongue pork belly beef ribs sausage enim ham aliquip.  Aute cow burgdoggen, sed pork loin hamburger leberkas minim.Ribeye spare ribs buffalo, sausage beef pork chop dolore fatback short ribs meatball jowl t-bone.  Pancetta deserunt boudin flank incididunt.  Consectetur id hamburger fatback, venison frankfurter ea.  Irure labore sausage, lorem commodo dolore ullamco et pariatur cupidatat ad biltong bresaola tongue meatball.  Fugiat pork loin boudin filet mignon. Tongue spare ribs cow bresaola.  Pastrami do kevin, biltong shankle incididunt aute chuck veniam pork loin eu venison cillum sed ut.  Flank non esse velit, nostrud pork loin nulla.  Jowl frankfurter in ham chicken.  Pork belly turkey ham hock, pork ut pig consequat cillum tenderloin.  Fugiat cow commodo tempor id pork bresaola alcatra aliqua strip steak dolore meatloaf pork belly aute. Jowl consequat corned beef cupim, frankfurter short loin non.  Anim doner ribeye, turducken beef dolore shoulder kielbasa t-bone magna hamburger tempor drumstick.  Capicola brisket bresaola ipsum, veniam pork hamburger chicken exercitation strip steak.  Esse aute dolore in prosciutto.  Pork frankfurter capicola, ham hock prosciutto flank rump strip steak elit non tri-tip bacon ball tip.  Ut short ribs minim, pork loin commodo incididunt ut.  Short ribs ex turducken bresaola.Jowl incididunt proident short loin chicken ham.  Spare ribs strip steak cupidatat tempor non fugiat in ribeye landjaeger sirloin.  Aliquip jowl hamburger capicola.  Occaecat pancetta chicken burgdoggen cupidatat picanha porchetta nostrud filet mignon.  Beef ribs dolore cupim lorem chislic flank culpa capicola shoulder. Dolore drumstick prosciutto, rump veniam exercitation shoulder duis biltong.");
        $classifier->learn("office ipsum", "Clear blue water. Waste of resources post launch we need to socialize the comms with the wider stakeholder community bench mark innovation is hot right now this vendor is incompetent start procrastinating 2 hours get to do work while procrastinating open book pretend to read while manager stands and watches silently nobody is looking quick do your web search manager caught you and you are fured. Bottleneck mice unlock meaningful moments of relaxation, but due diligence, but we need to get all stakeholders up to speed and in the right place, for Q1, so globalize, and organic growth. 360 degree content marketing pool manage expectations. Business impact we need to harvest synergy effects quick sync when does this sunset? , so drill down closer to the metal your work on this project has been really impactful. Run it up the flagpole, ping the boss and circle back level the playing field. One-sheet window-licker. Core competencies optimize the fireball, and drive awareness to increase engagement draw a line in the sand manage expectations, for reinvent the wheel what's our go to market strategy?. It's not hard guys iâ€™ve been doing some research this morning and we need to better. Big picture slipstream, so this vendor is incompetent , organic growth. Collaboration through advanced technlogy nail jelly to the hothouse wall, yet regroup, yet nail it down, for wiggle room. Can we parallel path obviously tbrand terrorists, for closing these latest prospects is like putting socks on an octopus a tentative event rundown is attached for your reference, including other happenings on the day you are most welcome to join us beforehand for a light lunch we would also like to invite you to other activities on the day, including the interim and closing panel discussions on the intersection of businesses and social innovation, and on building a stronger social innovation eco-system respectively usabiltiy, and products need full resourcing and support from a cross-functional team in order to be built, maintained, and evolved. We need to button up our approach time to open the kimono, cadence out of scope. Slipstream out of the loop game-plan, and collaboration through advanced technlogy donuts in the break room today shall be a cloudy day, thanks to blue sky thinking, we can now deploy our new ui to the cloud . Zoom meeting at 2:30 today code, so staff engagement game-plan, yet driving the initiative forward going forward. The last person we talked to said this would be ready we've bootstrapped the model value prop, nor marketing computer development html roi feedback team website, so deliverables.");
        $classifier->learn("office ipsum", "Cannibalize we want to see more charts spinning our wheels. To be inspired is to become creative, innovative and energized we want this philosophy to trickle down to all our stakeholders can you ballpark the cost per unit for me, but cc me on that we need to think big start small and scale fast to energize our clients. Land the plane incentivize adoption deliverables we are running out of runway, but what the, but out of the loop. Run it up the flag pole reach out, or to be inspired is to become creative, innovative and energized we want this philosophy to trickle down to all our stakeholders we should have a meeting to discuss the details of the next meeting, incentivize adoption. Marketing, illustration pixel pushing, yet we're ahead of the curve on that one, for open door policy. Crank this out optimize the fireball gain alignment product market fit, so beef up waste of resources, for we need a recap by eod, cob or whatever comes first. It is all exactly as i said, but i don't like it. Deploy put your feelers out, onward and upward, productize the deliverables and focus on the bottom line bake it in up the flagpole bazooka that run it past the boss jump right in and banzai attack will they won't they its all greek to me unless they bother until the end of time maybe vis a vis too many cooks over the line. Your work on this project has been really impactful if you're not hurting you're not winning, yet i called the it department about that ransomware because of the old antivirus, but he said that we were using avast 2021 value prop, or on this journey. Good optics don't over think it cross sabers, yet sorry i didn't get your email drink from the firehose we need to touch base off-line before we fire the new ux experience, so what's our go to market strategy?. Put it on the parking lot punter on this journey, but we need this overall to be busier and more active minimize backwards overflow creativity requires you to murder your children, so if you're not hurting you're not winning. What the draft policy ppml proposal, we just need to put these last issues to bed. Cadence organic growth let's prioritize the low-hanging fruit, for time to open the kimono let's prioritize the low-hanging fruit, yet start procrastinating 2 hours get to do work while procrastinating open book pretend to read while manager stands and watches silently nobody is looking quick do your web search manager caught you and you are fured. Dogpile that blue sky thinking we need to dialog around your choice of work attire, nor exposing new ways to evolve our design language, or peel the onion mobile friendly one-sheet. ");

        $loremIpsumResult = $classifier->classify("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in elementum nunc. Donec dapibus aliquam rutrum. Vestibulum hendrerit massa sit amet enim viverra ultrices. Vestibulum non dictum sapien, nec volutpat arcu. Donec congue ipsum ut arcu tristique, quis congue sem euismod. Cras tempor tortor pellentesque convallis venenatis. Nulla efficitur dictum felis, ut eleifend magna dignissim ut. Donec purus risus, auctor in malesuada at, finibus ut est. Aenean gravida augue dolor, eget porta purus fringilla vel. Etiam pharetra nisi vulputate felis euismod porta. Curabitur aliquam ligula in ex ultrices, eu porta ex posuere.Etiam ultrices ornare tincidunt. Vestibulum convallis dolor sapien, vel interdum orci posuere ac. Nulla et orci et ipsum dapibus pulvinar sed nec lorem. Curabitur tincidunt dolor urna, eget ullamcorper lorem condimentum quis. Curabitur hendrerit augue lorem, eu pharetra ipsum ultrices sed. Etiam pulvinar tortor ac mi lacinia cursus. Integer vulputate varius odio iaculis maximus. Maecenas malesuada mi sit amet metus hendrerit, ac gravida lectus venenatis. Nam suscipit turpis nunc, non porttitor nulla semper eget. Donec dictum tempus nisl gravida facilisis. Praesent vulputate tempor lacus id sodales. Vestibulum iaculis nulla ac porttitor commodo. Nulla hendrerit at nulla at lacinia.Donec mattis gravida tellus. Etiam neque massa, dictum a mattis sed, pharetra in metus. Duis ullamcorper pellentesque mollis. Donec sodales mollis orci vel tristique. Mauris neque nisl, cursus euismod mattis eu, faucibus at arcu. Fusce rutrum lorem odio, ac rhoncus velit porta ac. Cras finibus mauris ac purus facilisis, et pulvinar lectus tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam ut urna lorem.Maecenas mattis augue sed orci consequat, ut gravida justo tristique. Proin fermentum dui vitae ante facilisis sodales. Aenean suscipit rhoncus sodales. Quisque accumsan urna non metus pharetra, sed blandit leo dapibus. Praesent a gravida odio. Donec ut lectus mi. In ullamcorper urna erat, eget condimentum leo suscipit non.Nulla varius pulvinar commodo. Curabitur vitae mollis ex, eget volutpat mi. Morbi pretium varius nisl, sed finibus mauris. Mauris eget tortor finibus, molestie nulla quis, lacinia nisl. In hac habitasse platea dictumst. Sed convallis finibus nunc, vitae semper arcu lobortis id. Sed mi nisl, ornare id odio in, congue fringilla eros. Nullam pellentesque elit a odio aliquam feugiat. Maecenas tincidunt, dui et varius pharetra, elit ligula interdum velit, vel mattis lacus massa quis felis. Morbi mattis id mauris varius sagittis.");
        $pirateIpsumResult = $classifier->classify("Nipper keelhaul red ensign shrouds booty scurvy maroon wherry spirits cutlass. Clipper line gally Privateer scourge of the seven seas crow's nest Corsair sutler galleon hardtack. Starboard lad capstan lookout brig deadlights yawl pirate hornswaggle nipper. Fore take a caulk piracy grog nipperkin man-of-war squiffy dead men tell no tales scourge of the seven seas hogshead. Wherry landlubber or just lubber carouser fire in the hole red ensign marooned starboard sheet pirate execution dock. Fire in the hole doubloon bounty fathom execution dock me splice the main brace tender run a rig dead men tell no tales. American Main run a shot across the bow Blimey fore pillage measured fer yer chains Corsair swab mizzen lad. Line aye tack grapple hempen halter splice the main brace jury mast starboard booty killick. Reef sails Sea Legs snow dance the hempen jig capstan haul wind salmagundi yardarm jib case shot. Killick pinnace square-rigged Shiver me timbers loaded to the gunwalls topmast tack sutler lugger snow. Grog draft gibbet black spot chase guns Plate Fleet execution dock rigging provost parley. Shrouds no prey, no pay aft long boat scallywag Spanish Main fire ship landlubber or just lubber ho Jack Tar. Starboard lad capstan lookout brig deadlights yawl pirate hornswaggle nipper. Fore take a caulk piracy grog nipperkin man-of-war squiffy dead men tell no tales scourge of the seven seas hogshead. Wherry landlubber or just lubber carouser fire in the hole red ensign marooned starboard sheet pirate execution dock. Fire in the hole doubloon bounty fathom execution dock me splice the main brace tender run a rig dead men tell no tales. American Main run a shot across the bow Blimey fore pillage measured fer yer chains Corsair swab mizzen lad. Line aye tack grapple hempen halter splice the main brace jury mast starboard booty killick. Yellow Jack parrel code of conduct list piracy crimp bucko rum coffer bilge. Lee skysail matey tackle Jack Ketch jack aft line Jack Tar boom. Red ensign weigh anchor aye crack Jennys tea cup belay jolly boat warp Arr hardtack grapple.Port spike lateen sail driver Davy Jones' Locker black spot grog gunwalls Jack Tar pressgang. Log run a rig cackle fruit lookout Brethren of the Coast Spanish Main draft red ensign cable transom. Execution dock lateen sail spyglass Shiver me timbers knave swing the lead strike colors flogging piracy interloper.Killick pinnace square-rigged Shiver me timbers loaded to the gunwalls topmast tack sutler lugger snow. Grog draft gibbet black spot chase guns Plate Fleet execution dock rigging provost parley.");
        $baconIpsumResult = $classifier->classify("Shoulder cupim leberkas meatball do sint.  Ut ipsum excepteur pancetta.  Aute eu alcatra officia flank t-bone.  Duis sirloin beef aliqua. Occaecat shoulder in tempor venison irure porchetta t-bone beef lorem dolore veniam duis.  Salami pork belly swine, sint nostrud bacon chicken reprehenderit id tempor qui cow esse.  Bresaola aliqua excepteur buffalo esse hamburger boudin picanha consequat nostrud exercitation.  Pariatur fatback alcatra irure ut magna rump boudin ut pancetta occaecat nostrud pork belly.  Laboris pariatur nisi nulla non beef voluptate brisket dolor jowl aliqua bacon exercitation.  Culpa ad aute t-bone, ea in corned beef tempor spare ribs velit. Beef ribs turducken meatloaf nisi.  Veniam anim pork belly capicola cillum dolore spare ribs pancetta est.  Labore buffalo porchetta, dolore tempor doner non officia.  Kevin sausage ea spare ribs nostrud aute salami.  Qui t-bone ut, meatball nisi tempor dolore rump aute kielbasa ipsum laboris aliqua. Incididunt tenderloin alcatra chuck short ribs.  Pig ea rump et pork belly.  Corned beef leberkas meatball sed picanha voluptate ex veniam.  Ut anim pork officia beef sausage, velit tail salami ea adipisicing voluptate. Commodo dolor minim frankfurter magna fatback qui reprehenderit.  Corned beef fugiat dolor, dolore adipisicing shoulder culpa tri-tip.  Ipsum tempor in turducken, bacon shoulder aliquip consectetur ut spare ribs short loin cupim officia.  Leberkas voluptate meatball kevin ea ipsum.  Ex brisket t-bone ad, porchetta pig ball tip.  Jerky consectetur laborum pariatur, alcatra sint aliquip sausage magna dolore ipsum doner pork belly strip steak.Beef do aute, beef ribs enim elit biltong hamburger anim ut pancetta spare ribs.  Ut chuck kevin minim aliqua labore jowl.  Cow chuck shank, officia meatball kielbasa short loin.  Beef ribs voluptate capicola, meatloaf id pig tongue labore ham minim pork loin turkey fatback deserunt.  Burgdoggen sint spare ribs, ham hock et sausage buffalo beef ribs laboris in incididunt aute andouille esse laborum. Doner in fugiat, laboris shank alcatra boudin incididunt meatball spare ribs capicola esse turkey.  Rump pork loin quis cupim dolore leberkas.  Esse sint qui ribeye.  Tail anim shankle consectetur, corned beef reprehenderit kevin ad.  Non sirloin in tri-tip ut andouille, tenderloin cupidatat duis chuck picanha veniam sed jowl dolor.  Pork chop mollit lorem burgdoggen consectetur ullamco aliqua excepteur. In tenderloin ipsum velit non, brisket pork est.  In alcatra et fatback dolore sunt, frankfurter leberkas meatball.  Aute tongue boudin kevin, ullamco sausage consectetur porchetta tempor.");
        $officeIpsumResult = $classifier->classify("360 degree content marketing pool a tentative event rundown is attached for your reference, including other happenings on the day you are most welcome to join us beforehand for a light lunch we would also like to invite you to other activities on the day, including the interim and closing panel discussions on the intersection of businesses and social innovation, and on building a stronger social innovation eco-system respectively i have a hard stop in an hour and half, for draft policy ppml proposal, yet going forward, yet they have downloaded gmail and seems to be working for now. Upsell cloud strategy programmatically work flows , yet turn the ship our competitors are jumping the shark. Workflow ecosystem. Roll back strategy a better understanding of usage can aid in prioritizing future efforts this is not the hill i want to die on, but we need to get all stakeholders up to speed and in the right place looks great, can we try it a different way dogpile that, so (let's not try to) boil the ocean (here/there/everywhere). Those options are already baked in with this model UX, or that ipo will be a game-changer, cross-pollination, or turd polishing pull in ten extra bodies to help roll the tortoise time to open the kimono. Please advise soonest. Throughput digitalize cross sabers, yet this is not the hill i want to die on, yet low engagement. Let's unpack that later let's unpack that later i know you're busy, for pulling teeth, and we need to crystallize a plan, nor don't over think it. Product market fit i also believe it's important for every member to be involved and invested in our company and this is one way to do so, for the horse is out of the barn cloud strategy, but ultimate measure of success, but deliverables cadence. Rock Star/Ninja timeframe, but deliverables, but strategic staircase, rock Star/Ninja. Organic growth i am dead inside, we need a paradigm shift turn the ship ensure to follow requirements when developing solutions. Value-added shelfware goalposts increase the resolution, scale it up we need a larger print. Cadence win-win-win make it a priority. You better eat a reality sandwich before you walk back in that boardroom. Hire the best. I just wanted to give you a heads-up (let's not try to) boil the ocean (here/there/everywhere) we need to make the new version clean and sexy, yet we need to start advertising on social media if you want to motivate these clowns, try less carrot and more stick. Bottleneck mice cc me on that pig in a python unlock meaningful moments of relaxation organic growth strategic fit. We don't want to boil the ocean market-facing, yet crisp ppt, and in an ideal world let's circle back tomorrow.");

        $this->assertSame(array_keys($loremIpsumResult)[0], "lorem ipsum");
        $this->assertSame(array_keys($pirateIpsumResult)[0], "pirate ipsum");
        $this->assertSame(array_keys($baconIpsumResult)[0], "bacon ipsum");
        $this->assertSame(array_keys($officeIpsumResult)[0], "office ipsum");
    }
}